name: posto
description: An app to create images with text and share them anywhere.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # apple icons
  cupertino_icons: ^1.0.2

  # design pattern and state management
  stacked: ^3.2.0
  stacked_services: ^1.0.0

  # native ui
  flutter_platform_widgets: ^3.2.0

  # firebase
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16

  # image related
  image_picker: ^0.8.7+1
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

  # fonts
  google_fonts: ^4.0.3

  # http
  http: ^0.13.5

  # env
  flutter_dotenv: ^5.0.2

  # share
  share_plus: ^6.3.1

  # path provider
  path_provider: ^2.0.14

  # connectivity
  connectivity_plus: ^3.0.3

  # annotations for code generation (freezed, json_serializable)
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2
  
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env

