// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yJQ9IOTXpWD8BkWv_6_erbkxYq6tl9o',
    appId: '1:236600038314:web:bcad8a1b49e43ab10351d3',
    messagingSenderId: '236600038314',
    projectId: 'creation-post-app',
    authDomain: 'creation-post-app.firebaseapp.com',
    databaseURL: 'https://creation-post-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'creation-post-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHu4xjyiy4KUsl37N6j6RK5zMgoXanV2Q',
    appId: '1:236600038314:android:2a1cdfab7cd7f77e0351d3',
    messagingSenderId: '236600038314',
    projectId: 'creation-post-app',
    databaseURL: 'https://creation-post-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'creation-post-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxMi5W2ZYNKnfNOnHhcpGGNjh2mzBgqE',
    appId: '1:236600038314:ios:ffd58d93ffc7ec7c0351d3',
    messagingSenderId: '236600038314',
    projectId: 'creation-post-app',
    databaseURL: 'https://creation-post-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'creation-post-app.appspot.com',
    iosClientId: '236600038314-jqdf5jn87mqof73tt2em4ap3a9n0botc.apps.googleusercontent.com',
    iosBundleId: 'com.example.posto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxMi5W2ZYNKnfNOnHhcpGGNjh2mzBgqE',
    appId: '1:236600038314:ios:ffd58d93ffc7ec7c0351d3',
    messagingSenderId: '236600038314',
    projectId: 'creation-post-app',
    databaseURL: 'https://creation-post-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'creation-post-app.appspot.com',
    iosClientId: '236600038314-jqdf5jn87mqof73tt2em4ap3a9n0botc.apps.googleusercontent.com',
    iosBundleId: 'com.example.posto',
  );
}
